### ISSUE TITLE
First class support for Cocapods

### ISSUE THREAD

**Issue by kkharji** [kkharji/xbase#193]
Experimenting with https://github.com/wojciech-kulik/Swift-MVVMC-Demo

**Status**:
- [x] Build/Run works fine
- [ ] LSP features

**Issues**:
 
- `pod install` needs to be ran manually for build/run to work
- Fails to generate compile commands. xcworkspace is totally ignored.

**Todos**:

- [ ] Generate compile commands based on project schema (see [tuist.rs support](https://github.com/kkharji/xbase/blob/master/src/project/tuist.rs#L59))
- [ ]  Automatically run pod install on Podfile and no Pods directory, as well as when Podfile is updated.

cc @wojciech-kulik

**Comment by wojciech-kulik** [comment]
I think at first approach you don't have to worry about running `pod install` automatically and detecting changes there. Usually people call it manually when working on the project.
